<?php
require_once(PATH_SYSTEM . '/core/DB.php');

class Model extends DB {

    public $tblName;
    // Class Cha là DB có tồn tại method selectRoomID này rồi thì class con chỉ nên viết lại khi có update method này thôi. Nếu không thì ko cần.
    // Thấy ko. Bỏ đi vẫn chạy bt. Tại vì ở bên Model register kia nó sẽ kế thừa thẳng từ thằng ông, ko cần thằng cha hiện tại này viết lại nữa.
//    function selectRoomID($table)
//    {
//        trường hợp viết lại chỉ khi em thêm 1 logic nào đó. VD:
//        $this->abc = 'xyzzzz';
        // cần chèn logic mới thì mới cần viết lại. ko thì ko cần. để nó kế thừa từ ông, cụ kị gì đó đi

//        return parent::selectRoomID($table); // TODO: Change the autogenerated stub
//    }
//    function selectDKUser($table, $conditions)
//    {
//        return parent::selectDKUser($table, $conditions); // TODO: Change the autogenerated stub
//    }

    function selectConditionAdmin()
    {
        return parent::selectConditionAdmin(); // TODO: Change the autogenerated stub
    }
    public function selectConditionUser()
    {
        return parent::selectConditionUser(); // TODO: Change the autogenerated stub
    }
    public function selectBySQL($table)
    {
        return parent::selectBySQL($table); // TODO: Change the autogenerated stub
    }
    public function selectAdmin($table, $conditions)
    {
        return parent::selectAdmin($table, $conditions); // TODO: Change the autogenerated stub
    }

    function select($table, $conditions) {

        return parent::select($table, $conditions);
    }

    public function insert($table, $record)
    {
        return parent::insert($table, $record); // TODO: Change the autogenerated stub
    }

    function update($table, $record, $conditions) {
        return parent::update($table, $record, $conditions);
    }

    function delete($table, $conditions) {
        return parent::delete($table, $conditions);
    }
    function getData($sql) {
        return parent::getData($sql);
    }
}
?>
